services:
  # Frontend Static Site
  - type: static
    name: nexus-frontend
    repo: https://github.com/MuhammadDanyall/Nexus
    branch: main
    rootDir: Nexus
    buildCommand: npm run build
    publishDir: dist
    routes:
      - source: /*
        destination: /index.html
        type: rewrite